[build-menu]
EX_00_LB=_Renumber BASIC program
EX_00_CM=$HOME/scripts/renumBASIC.sh %f %f 10
EX_00_WD=%d
EX_01_LB=Build Coco 2 DSK image and launch MAME (local)
EX_01_CM=$HOME/scripts/makeDSK.sh coco2 n
EX_01_WD=%d
EX_02_LB=Build Coco 2 DSK image and launch MAME (pyDW)
EX_02_CM=$HOME/scripts/makeDSK.sh coco2 y
EX_02_WD=%d
EX_03_LB=Build Coco 2 DSK image and launch XRoar (local)
EX_03_CM=$HOME/scripts/makeDSK-XRoar.sh coco2bus n
EX_03_WD=%d
EX_04_LB=Build Coco 2 DSK image and launch XRoar (pyDW)
EX_04_CM=$HOME/scripts/makeDSK-XRoar.sh coco2bus y
EX_04_WD=%d
EX_05_LB=Build Coco 3 DSK image and launch MAME (local)
EX_05_CM=$HOME/scripts/makeDSK.sh coco3 n
EX_05_WD=%d
EX_06_LB=Build Coco 3 DSK image and launch MAME (pyDW)
EX_06_CM=$HOME/scripts/makeDSK.sh coco3dw1 y
EX_06_WD=%d
EX_07_LB=Build Coco 3 DSK image and launch XRoar (local)
EX_07_CM=$HOME/scripts/makeDSK-XRoar.sh coco3 n
EX_07_WD=%d
EX_08_LB=Build Coco 3 DSK image and launch XRoar (pyDW)
EX_08_CM=$HOME/scripts/makeDSK-XRoar.sh coco3 y
EX_08_WD=%d
EX_09_LB=Compile assembly program (lwasm)
EX_09_CM=/usr/bin/lwasm --6809 --decb --output=%d/%e.bin %d/%f
EX_09_WD=%d
EX_10_LB=Compile assembly program (asm6809)
EX_10_CM=/usr/local/bin/asm6809 --coco --output=%d/%e.bin %d/%f
EX_10_WD=%d
EX_11_LB=Compile C program (CMOC)
EX_11_CM=/usr/bin/cmoc -o %d/%e.bin %d/%f
EX_11_WD=%d
EX_12_LB=Create BASIC MC-10 WAV file and launch MAME (local)
EX_12_CM=$HOME/scripts/makeWAV-mc10.sh mc10 n
EX_12_WD=%d
EX_13_LB=Create BASIC MC-10 WAV file and launch XRoar (local)
EX_13_CM=$HOME/scripts/makeWAV-mc10-XRoar.sh mc10
EX_13_WD=%d
EX_14_LB=Create BASIC MC-10 WAV file and launch MAME (pyDW)
EX_14_CM=$HOME/scripts/makeWAV-mc10.sh mcx128 y
EX_14_WD=%d
EX_15_LB=Compile MC-10 BASIC program (mcbasic)
EX_15_CM=$HOME/scripts/compile-BASIC-mc10.sh %d/%f
EX_15_WD=%d
EX_16_LB=Compile BASIC program (ugBasic - CoCo)
EX_16_CM=/usr/local/bin/ugbc.coco -L %d/%e.lst -O bin %d/%e.bas -o %d/%e.bin
EX_16_CM_WD=%d

